FROM php:8.1.0-cli-alpine3.15

COPY ./docker/php.ini /usr/local/etc/php/conf.d/99-overrides.ini

RUN docker-php-ext-install pdo_mysql \
    && docker-php-ext-enable pdo_mysql

RUN apk add --update --no-cache ${PHPIZE_DEPS}\
    && pecl install xdebug-3.1.2 \
    && docker-php-ext-enable xdebug \
    && apk del ${PHPIZE_DEPS}

RUN apk add --update --no-cache bash \
    && curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash \
    && apk add symfony-cli

RUN wget -q "https://github.com/go-task/task/releases/download/v3.13.0/task_linux_amd64.tar.gz" || exit 1 \
    && tar -xf task_linux_amd64.tar.gz task \
    && mv task /usr/bin/task

WORKDIR /app

COPY . /app

RUN wget -q https://getcomposer.org/installer && php installer --install-dir=/usr/bin --filename=composer \
    && rm -f installer \
    && composer install

RUN adduser -D -s /bin/sh -u 1000 user
USER user

