FROM php:8.1.0-cli-alpine3.15

COPY ./docker/php.ini /usr/local/etc/php/conf.d/99-overrides.ini

RUN apk add --no-cache ${PHPIZE_DEPS}\
    && pecl install xdebug-3.1.2 \
    && docker-php-ext-enable xdebug \
    && apk del ${PHPIZE_DEPS}

RUN apk add --no-cache bash \
    && curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash \
    && apk add symfony-cli

WORKDIR /application

COPY . /application

RUN wget -q https://getcomposer.org/installer && php installer --install-dir=/usr/bin --filename=composer \
    && rm -f installer \
    && composer install

RUN adduser -D -s /bin/sh -u 1000 user
USER user

