services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Tests\Factories\:
        resource: '%kernel.project_dir%/tests/Factories/*'

    Tests\Mocks\:
        resource: '%kernel.project_dir%/tests/Mocks/*'

    Tests\Mocks\EventDispatcher:
        arguments:
            $eventDispatcher: '@event_dispatcher'

    Psr\EventDispatcher\EventDispatcherInterface:
        alias: 'Tests\Mocks\EventDispatcher'

    Tests\Mocks\MessageBus:
        arguments:
            $messageBus: '@messenger.bus.default'

    Symfony\Component\Messenger\MessageBusInterface:
        alias: 'Tests\Mocks\MessageBus'