parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/Domain/'
            - '%kernel.project_dir%/src/Kernel.php'

    App\Application\MeasurementRepositoryInterface:
        alias: App\Port\Mysql\Repository\MeasurementRepository

    App\Application\AlertRepositoryInterface:
        alias: App\Port\Mysql\Repository\AlertRepository

