parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'

    App\Application\MeasurementRepositoryInterface:
        alias: App\Port\Mysql\Repository\MeasurementRepository
