parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '%kernel.project_dir%/src/'
        exclude:
            - '%kernel.project_dir%/src/Domain/'
            - '%kernel.project_dir%/src/Kernel.php'

    App\Application\AlertReadRepositoryInterface:
        alias: App\Port\Mysql\Repository\AlertReadRepository

    App\Port\Api\Rest\QueryParamConverter:
        tags:
            - { name: request.param_converter, converter: param_converter.query }

